name: Example Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install the dependencies
        run: npm ci

      - name: Run local action
        uses: ./.github/actions/hello-world
        with:
          name: "Peter"
